/**
 * @fileoverview gRPC-Web generated client stub for runner
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.1
// source: runner.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.runner = require('./runner_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.runner.RunnerClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.runner.RunnerPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.runner.RunnerRequest,
 *   !proto.runner.RunnerResponse>}
 */
const methodDescriptor_Runner_Run = new grpc.web.MethodDescriptor(
  '/runner.Runner/Run',
  grpc.web.MethodType.UNARY,
  proto.runner.RunnerRequest,
  proto.runner.RunnerResponse,
  /**
   * @param {!proto.runner.RunnerRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.runner.RunnerResponse.deserializeBinary
);


/**
 * @param {!proto.runner.RunnerRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.runner.RunnerResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.runner.RunnerResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.runner.RunnerClient.prototype.run =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/runner.Runner/Run',
      request,
      metadata || {},
      methodDescriptor_Runner_Run,
      callback);
};


/**
 * @param {!proto.runner.RunnerRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.runner.RunnerResponse>}
 *     Promise that resolves to the response
 */
proto.runner.RunnerPromiseClient.prototype.run =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/runner.Runner/Run',
      request,
      metadata || {},
      methodDescriptor_Runner_Run);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.runner.RunnerRequest,
 *   !proto.runner.RunnerResponse>}
 */
const methodDescriptor_Runner_ServerStreaming = new grpc.web.MethodDescriptor(
  '/runner.Runner/ServerStreaming',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.runner.RunnerRequest,
  proto.runner.RunnerResponse,
  /**
   * @param {!proto.runner.RunnerRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.runner.RunnerResponse.deserializeBinary
);


/**
 * @param {!proto.runner.RunnerRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.runner.RunnerResponse>}
 *     The XHR Node Readable Stream
 */
proto.runner.RunnerClient.prototype.serverStreaming =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/runner.Runner/ServerStreaming',
      request,
      metadata || {},
      methodDescriptor_Runner_ServerStreaming);
};


/**
 * @param {!proto.runner.RunnerRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.runner.RunnerResponse>}
 *     The XHR Node Readable Stream
 */
proto.runner.RunnerPromiseClient.prototype.serverStreaming =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/runner.Runner/ServerStreaming',
      request,
      metadata || {},
      methodDescriptor_Runner_ServerStreaming);
};


module.exports = proto.runner;

